### ISSUE TITLE
Autoscroll features not working

### ISSUE THREAD

**Issue by whupdido** [Tyson3101/Auto-Youtube-Shorts-Scroller#30]
The minimum view and like count feature suddenly stopped working today. I tried uninstalling reinstalling and even tried installing the newer version
![image](https://github.com/Tyson3101/Auto-Youtube-Shorts-Scroller/assets/88324453/c5556210-8dcd-4439-ade5-44ae1d3e8a46)
![image](https://github.com/Tyson3101/Auto-Youtube-Shorts-Scroller/assets/88324453/a7fc1729-2231-47f0-9073-4498218ee5ce)

**Comment by whupdido** [comment]
Also to add to this, it will skip shorts it is not supposed to for no apparent reason

**Comment by dragonfly27** [comment]
Same here.  Was working the last few months until a few days ago. Uninstalled/reinstalled about 10 times.  Rebooted.  Worked for a few minutes yesterday out of the blue, now back to not working (Chrome [Chrome is up to date,
Version 122.0.6261.70 (Official Build) (64-bit)] or chrome app).

**Comment by Tyson3101** [comment]
Hey Thanks for bringing this up, seems like Youtube had a small UI update with the class names messing up the selectors of the like count, etc.
I have just published an update to the extension which should have the features fixed. It may take a day or two to be updated on the web store.

Thanks again and let me know if you face any other issues

**Comment by whupdido** [comment]
Works perfectly now, thank you :)

**Comment by dragonfly27** [comment]
Sorry, still not working for me.  Tried multiple times reinstalling Version
2.5.2.
